name: Check run
on:
  push:
    branches:
      - main
jobs:
  logLatestRelease:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: PUT /repos/damienoleary/kombucha-calculator/pulls/22/update-branch
          expected_head_sha: 4dfa00ff7dfbd2b4b5d97f0b2f2f9d768cba5f8b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
  triggerDeployment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: POST /repos/damienoleary/kombucha-calculator/actions/workflows/deploy_pr.yml/dispatches
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"