name: Check run
on:
  push:
    branches:
      - main
jobs:
  logLatestRelease:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: PUT /repos/damienoleary/kombucha-calculator/pulls/{pull_number}/update-branch
          expected_head_sha: 37c702ada2058ac9db051dd8a342b1a1e7f31ed9
          pull_number: 22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_ID: 22
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
  triggerDeployment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: POST /repos/damienoleary/kombucha-calculator/actions/workflows/deploy_pr.yml/dispatches
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"