name: Check run
on:
  push:
    branches:
      - main
jobs:
  logLatestRelease:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: PUT /repos/damienoleary/kombucha-calculator/pulls/22/update-branch
          mediatType: application/json
          body: '{"expected_head_sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"